export const mockCases = [
  {
    id: "1",
    token: "abc123",
    referenceNo: "LN001234",
    customerName: "Rajesh Kumar",
    customerEmail: "rajesh@example.com",
    tags: ["Home Loan", "Priority"],
    status: "partial",
    storageMode: "structured",
    createdAt: "2026-04-20",
    totalItems: 5,
    uploadedItems: 3,
    checklist: [
      { id: "c1", name: "PAN Card", required: true, allowMultiple: false, status: "uploaded", files: ["pan_rajesh.pdf"] },
      { id: "c2", name: "Aadhaar Card", required: true, allowMultiple: true, status: "uploaded", files: ["aadhaar_front.jpg", "aadhaar_back.jpg"] },
      { id: "c3", name: "Salary Slip", required: true, allowMultiple: true, status: "uploaded", files: ["salary_march.pdf"] },
      { id: "c4", name: "Bank Statement", required: true, allowMultiple: false, status: "pending", files: [] },
      { id: "c5", name: "Passport Photo", required: false, allowMultiple: false, status: "pending", files: [] },
    ],
  },
  {
    id: "2",
    token: "def456",
    referenceNo: "HR002891",
    customerName: "Priya Sharma",
    customerEmail: "priya@example.com",
    tags: ["Onboarding", "Engineering"],
    status: "complete",
    storageMode: "flat",
    createdAt: "2026-04-18",
    totalItems: 4,
    uploadedItems: 4,
    checklist: [
      { id: "c1", name: "Resume", required: true, allowMultiple: false, status: "uploaded", files: ["resume_priya.pdf"] },
      { id: "c2", name: "Offer Letter Signed", required: true, allowMultiple: false, status: "uploaded", files: ["offer_signed.pdf"] },
      { id: "c3", name: "ID Proof", required: true, allowMultiple: false, status: "uploaded", files: ["passport_priya.jpg"] },
      { id: "c4", name: "Education Certificate", required: true, allowMultiple: true, status: "uploaded", files: ["degree.pdf", "marksheet.pdf"] },
    ],
  },
  {
    id: "3",
    token: "ghi789",
    referenceNo: "INS003456",
    customerName: "Amit Patel",
    customerEmail: "amit@example.com",
    tags: ["Insurance Claim", "Motor"],
    status: "pending",
    storageMode: "structured",
    createdAt: "2026-04-22",
    totalItems: 6,
    uploadedItems: 0,
    checklist: [
      { id: "c1", name: "Claim Form", required: true, allowMultiple: false, status: "pending", files: [] },
      { id: "c2", name: "RC Book", required: true, allowMultiple: false, status: "pending", files: [] },
      { id: "c3", name: "Driving License", required: true, allowMultiple: false, status: "pending", files: [] },
      { id: "c4", name: "FIR Copy", required: true, allowMultiple: false, status: "pending", files: [] },
      { id: "c5", name: "Repair Estimate", required: true, allowMultiple: true, status: "pending", files: [] },
      { id: "c6", name: "Photos of Damage", required: false, allowMultiple: true, status: "pending", files: [] },
    ],
  },
  {
    id: "4",
    token: "jkl012",
    referenceNo: "RE004120",
    customerName: "Sunita Verma",
    customerEmail: "sunita@example.com",
    tags: ["Property Purchase", "Resale"],
    status: "partial",
    storageMode: "structured",
    createdAt: "2026-04-21",
    totalItems: 5,
    uploadedItems: 2,
    checklist: [
      { id: "c1", name: "Sale Agreement", required: true, allowMultiple: false, status: "uploaded", files: ["agreement.pdf"] },
      { id: "c2", name: "Property Title Deed", required: true, allowMultiple: false, status: "uploaded", files: ["title_deed.pdf"] },
      { id: "c3", name: "NOC from Society", required: true, allowMultiple: false, status: "pending", files: [] },
      { id: "c4", name: "Latest Tax Receipt", required: true, allowMultiple: false, status: "pending", files: [] },
      { id: "c5", name: "Encumbrance Certificate", required: false, allowMultiple: false, status: "pending", files: [] },
    ],
  },
];

export const mockTemplates = [
  { id: "t1", name: "Home Loan KYC", itemCount: 7 },
  { id: "t2", name: "Employee Onboarding", itemCount: 6 },
  { id: "t3", name: "Insurance Claim", itemCount: 8 },
  { id: "t4", name: "Property Due Diligence", itemCount: 9 },
  { id: "t5", name: "Business Loan", itemCount: 11 },
];

export const mockStats = {
  total: 24,
  pending: 8,
  partial: 10,
  complete: 6,
  documentsCollected: 143,
};
